//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress
    {
        public int AddressId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsMainAddr { get; set; }
        public int MemberId { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
