//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErpOrder
    {
        public int id { get; set; }
        public string mail { get; set; }
        public string itemsns { get; set; }
        public string prices { get; set; }
        public string nums { get; set; }
        public string receiver_name { get; set; }
        public string receiver_address { get; set; }
        public string receiver_state { get; set; }
        public string receiver_city { get; set; }
        public string receiver_district { get; set; }
        public string logistics_type { get; set; }
        public string outer_tid { get; set; }
        public string outer_shop_code { get; set; }
        public string receiver_mobile { get; set; }
        public string outer_ddly { get; set; }
        public string buyer_message { get; set; }
        public string logistics_fee { get; set; }
        public string pay_moneys { get; set; }
        public string ticket_no { get; set; }
        public Nullable<System.DateTime> pay_datatimes { get; set; }
        public string err_message { get; set; }
        public System.DateTime ctime { get; set; }
        public bool isresend { get; set; }
        public string skusns { get; set; }
    }
}
