//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manger
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string OpenID { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string Lng { get; set; }
        public string Lat { get; set; }
        public Nullable<decimal> Proportion { get; set; }
        public string Category { get; set; }
        public Nullable<int> IsRecommend { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string Contacts { get; set; }
        public string license { get; set; }
        public string Storefront { get; set; }
        public string Phone { get; set; }
        public string Business { get; set; }
        public string Introduce { get; set; }
        public Nullable<int> State { get; set; }
    }
}
