//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public string OpenId { get; set; }
        public string NickName { get; set; }
        public byte Gender { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string HeadImgUrl { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string ContactAddr { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string OrignKey { get; set; }
        public Nullable<int> LastLoginDate { get; set; }
        public Nullable<int> LoginDate { get; set; }
        public string UserName { get; set; }
        public string QQ { get; set; }
        public string Birth { get; set; }
        public string District { get; set; }
        public string follow { get; set; }
        public string balance { get; set; }
        public string Cashbalance { get; set; }
        public Nullable<int> fsate { get; set; }
        public Nullable<int> ISVip { get; set; }
        public Nullable<decimal> integral { get; set; }
        public Nullable<decimal> TotalIn { get; set; }
    }
}
