//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MircoShopEntities : DbContext
    {
        public MircoShopEntities()
            : base("name=MircoShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual DbSet<GroupRelation> GroupRelations { get; set; }
        public virtual DbSet<MemberCoupon> MemberCoupons { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductGroup> ProductGroups { get; set; }
        public virtual DbSet<ProductImg> ProductImgs { get; set; }
        public virtual DbSet<ProductOrder> ProductOrders { get; set; }
        public virtual DbSet<ReturnOrder> ReturnOrders { get; set; }
        public virtual DbSet<HomeImage> HomeImages { get; set; }
        public virtual DbSet<ProductSaleGroup> ProductSaleGroups { get; set; }
        public virtual DbSet<GroupSaleRelation> GroupSaleRelations { get; set; }
        public virtual DbSet<OrderProductDetail> OrderProductDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryRelation> CategoryRelations { get; set; }
        public virtual DbSet<UserCoupon> UserCoupons { get; set; }
        public virtual DbSet<SaleRule> SaleRules { get; set; }
        public virtual DbSet<ErpOrder> ErpOrders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<MeIntegral> MeIntegrals { get; set; }
        public virtual DbSet<Withdrawal> Withdrawals { get; set; }
        public virtual DbSet<OrderComment> OrderComments { get; set; }
        public virtual DbSet<OrderReturn> OrderReturns { get; set; }
        public virtual DbSet<ProductBrand> ProductBrands { get; set; }
        public virtual DbSet<Recharge> Recharges { get; set; }
        public virtual DbSet<Manger> Mangers { get; set; }
        public virtual DbSet<GiftList> GiftLists { get; set; }
        public virtual DbSet<IntList> IntLists { get; set; }
        public virtual DbSet<MangerCate> MangerCates { get; set; }
    }
}
