//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCoupon
    {
        public int CouponId { get; set; }
        public string OpenId { get; set; }
        public int Amount { get; set; }
        public int Consum { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> ValidityDate { get; set; }
        public Nullable<int> PeriodDate { get; set; }
        public Nullable<int> CreateDate { get; set; }
        public int IsUse { get; set; }
        public string Original { get; set; }
        public string OrderNum { get; set; }
    }
}
