//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCloudShop.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> DZTime { get; set; }
        public Nullable<int> State { get; set; }
        public string Remack { get; set; }
        public string TrueName { get; set; }
        public string Bank { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Types { get; set; }
    }
}
